x-common: &common
    image: "${APP_NAME:-lighting}:${APP_ENV:-local}"

x-app: &app
    <<: *common
    volumes:
        - .:/var/www/app
    depends_on:
        - builder
        - pgsql
        - redis

services:
    builder:
        build:
            dockerfile: ./deploy/php/Dockerfile
            target: ${APP_ENV:-local}
        <<: *common

    app:
        <<: *app
        ports:
            - "${APP_PORT:-80}:80"
        command: php -d variables_order=EGPCS artisan serve --host=0.0.0.0 --port=${APP_PORT:-80}

    worker:
        <<: *app
        command: php artisan horizon

    scheduler:
        <<: *app
        command: php artisan schedule:work

    pgsql:
        image: postgres:15
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE:-lighting}
            POSTGRES_USER: ${DB_USERNAME:-app}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - app-pgsql:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - app-redis:/data

volumes:
    app-pgsql:
    app-redis:
