x-app: &app
    build:
        context: ./deploy/php
        dockerfile: Dockerfile
        target: ${COMPOSE_TARGET:-dev}
    volumes:
        - .:/var/www/app

services:
    app:
        <<: *app
        ports:
            - "${APP_PORT:-80}:80"
        depends_on:
            - pgsql
            - redis
        command: "php -d variables_order=EGPCS /var/www/app/artisan serve --host=0.0.0.0 --port=${APP_PORT:-80}"

    worker:
        <<: *app
        command: php /var/www/app/artisan horizon
        restart: unless-stopped

    scheduler:
        <<: *app
        command: php /var/www/app/artisan schedule:work
        restart: unless-stopped

    pgsql:
        image: postgres:15
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - app-pgsql:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - app-redis:/data

volumes:
    app-pgsql:
    app-redis:
